### PR TITLE
68 allow base type to be specified

### PR DESCRIPTION
**Pull request by dconder**
First pull req on this project, so please let me know if I need to do anything else. This adds a BaseClass option, that, if set, will create a blank base class and an extender class that uses partials to make each output class derive from that.

### CODE REVIEW

**Comment by petrsvihlik** [comment]
@dconder thanks! could you please make sure all [tests are passing](https://ci.appveyor.com/project/kentico/cloud-generators-net/build/1.5.160/tests)

**Comment by dconder** [comment]
@petrsvihlik  Sorry, the text files weren't configured to copy to the output folder. Tests passing.

**Comment by Simply007** [comment]
@dconder - I went through the code briefly and it looks OK. I will make a proper review hopefully tomorrow and merge it to the master.

**Comment by dconder** [comment]
Hi @Simply007 , 

I’ve made the requested updates. There are now three tests. I also ran it by SonarQube and it’s green on my side. I had to keep the regex whitespace cleanup because while the tests are green locally, after being pushed into git, there were differences in line endings and the tests were failing in appveyor.

**Comment by Simply007** [comment]
Thanks for the updated @dconder!
I have went through the changes and everything looks fine!

I will tak a look to the app veyor, why it is failing when the line endings should be ignored.

Sorry for the delay, we had a national holiday last Thursday and Friday.

Have a nice day,
@dconder

**Comment by Simply007** [comment]
Could you send me the result of the command:
```
git config --global --get-all core.autocrlf
git config --local--get-all core.autocrlf
```

**Comment by Simply007** [comment]
I have tried to remove the regex filter and use the parameters and my build succeeded on AppVeyor:
* https://ci.appveyor.com/project/kentico/cloud-generators-net

**Comment by dconder** [comment]
@Simply007 
git config --global --get-all core.autocrlf  >> returns "true"
git config --local--get-all core.autocrlf >> returns nothing

**Comment by Simply007** [comment]
Thank @dconder. As I wrote in the previous comment, I have removed regular expression striping and it has worked.

I would like to leave it that way and if this error shows up again, I might be more successful in reproducing the issue.

**Pull request merged**
